### ISSUE TITLE
[BUG]设置了redis无效，设置keyPrefix也无效

### ISSUE THREAD

**Issue by athenakia** [asjdf/gorm-cache#15]
设置了redis无效，还是使用内存，设置keyPrefix也无效。下面代码的判断逻辑有问题。

https://github.com/asjdf/gorm-cache/blob/c704ff7950e9340cd33a40d6ebf6e9c3c6e2925e/cache/cache.go#L79

在这行判断代码之前，`c.cache`之前一直是nil。

设置keyPrefix无效是因为除了在ResetCache的CleanCache中使用之外，其他地方几乎没有用过这个值。。。

**Comment by asjdf** [comment]
非常感谢您的报告，该错误已在v1.2.3版本中修正
